name: Release 
run-name: ${{github.actor}} is releasing ${{github.event_name}} for ${{github.repository}}

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

  Pnpm-Check-Version:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Check pnpm version
        run: pnpm --version
  
  Pnpm-Install:
    runs-on: ubuntu-latest
    needs: [Pnpm-Check-Version]
    steps:
      - name: Install pnpm
        run: npm install -g pnpm